[build]
publish = "public"
command = "yarn build"
functions = "lambda"
[build.environment]
NODE_VERSION = "14"
YARN_VERSION = "1.22.15"
YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
from = "/myspaceimages/*"
to = "https://cdn.ppfhouse.com/myspaceimages/:splat"
status = 301

[[redirects]]
from = "/flutter/*"
to = "https://flutter.ppfhouse.com/"
status = 301

[[redirects]]
from = "/music/wpbe/"
to = "/wpbe/"
status = 301

[[redirects]]
from = "/music/leo37/*"
to = "https://www.facebook.com/037vudu"
status = 302

[[redirects]]
from = "/*"
to = "/"
status = 302
